### ISSUE TITLE
Question: onLogLine - how to capture it now?

### ISSUE THREAD

**Issue by bsides** [hibiyasleep/OverlayPlugin#20]
Hi @hibiyasleep,

I would like to know how to capture `/echo` ingame messages now that onLogLine isn't in miniparse anymore... is there any way without having to create another logparser window and subscribing to it? Looks like a lot to ask for the regular user.

Thank you!

**Comment by hibiyasleep** [comment]
Currently `onLogLine` implementation of Mini Parse may fail, because Miniparse excepts messages are not parsed/formatted by FFXIV_Plugin, but `beforeLogLine` handler assigning is on race-condition; use of Logparse is preferred, and Miniparse logline will deprecated. (Logparse can still receive Encounter data)

**Comment by bsides** [comment]
I don't know if I understood it right but does it mean I'll have to ask the users to use Logparse instead of Miniparse if I want to be able to do something when the user types `/e something`? I'm sorry, english isn't my first language as well 😢

**Comment by hibiyasleep** [comment]
Sorry I'm also bad at english :(, here's abstract:

* Miniparse `/e` implementation has critical problem, and this will deprecated;
* You (and user) should use Logparse, log filter will be added later.

**Comment by bsides** [comment]
Alright, I got it correct then. I think the name is somewhat misleading, but I'm looking forward for your development. Unfortunatelly I can't help much in C#

Thanks @hibiyasleep ^^
